# Generated by Django 6.0.4 on 2026-05-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='room',
            name='size',
            field=models.CharField(max_length=6),
        ),
    ]
