# Generated by Django 6.0.4 on 2026-06-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('owner', 'Owner'), ('tenant', 'Tenant'), ('prospect', 'Prospective Tenant')], default='tenant', max_length=10),
        ),
    ]
