# Generated by Django 6.0.4 on 2026-06-13 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_email_verified'),
        ('core', '0002_room_owner_roomrequest'),
    ]

    operations = [
    ]
