# Generated by Django 6.0.4 on 2026-06-15 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tenant_status',
        ),
    ]
