# Generated by Django 6.0.4 on 2026-06-15 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_20260614_0040'),
        ('core', '0003_remove_profile_tenant_status'),
    ]

    operations = [
    ]
