# Generated by Django 6.0.4 on 2026-06-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20260615_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tenant_status',
            field=models.CharField(blank=True, choices=[('new', 'New Tenant'), ('verified', 'Verified Tenant')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='ic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='moveindate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
