# Generated by Django 6.0.4 on 2026-06-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_tenant_status_alter_tenant_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('assigned', 'Assigned')], default='pending', max_length=20),
        ),
    ]
