# Generated by Django 6.0.4 on 2026-06-21 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_roomrequest_status'),
        ('core', '0006_alter_roomrequest_status_chatmessage'),
    ]

    operations = [
    ]
