# Generated by Django 6.0.4 on 2026-06-08 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rentalcontract'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RentalContract',
        ),
    ]
