# Generated by Django 6.0.4 on 2026-06-20 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_delete_rentalcontract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('duration_months', models.IntegerField(choices=[(6, '6 months'), (12, '12 months'), (24, '24 months')], default=12)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('electric_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('water_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
