# Generated by Django 6.0.4 on 2026-06-20 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_rentalcontract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='against_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints_against', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('tenant_to_owner', 'Tenant Complaint (about property)'), ('owner_to_tenant', 'Owner Complaint (about tenant)')], default='tenant_to_owner', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints_filed', to=settings.AUTH_USER_MODEL),
        ),
    ]
